# experiment params
NUM_SEEDS: 1
SEED: 0

# if  hyperparameters tuning
HYP_TUNE: False

# continual RL experiment (set to true via CLI or override config)
CONTINUAL_EXPERIMENT: True

# wandb params
WANDB_MODE: "online"  # set to online to activate wandb
ENTITY: ""
PROJECT: "debug"
alg:
  WANDB_LOG_ALL_SEEDS: False # will log all the vmapped seeds separetely

# where to save the params (if None, will not save)
SAVE_PATH: "./models"